export const SKILLS = [{
  title: 'Javascript',
  src: 'icons8-javascript-100.svg',
}, {
  title: 'Typescript',
  src: 'icons8-typescript-100.svg',
}, {
  title: 'React',
  src: 'icons8-react-100.svg',
}, {
  title: 'NextJs',
  src: 'icons8-nextjs-100.svg',
}, {
  title: 'Redux',
  src: 'icons8-redux-100.svg',
}, {
  title: 'Redux Saga',
  src: 'redux-saga.svg',
}, {
  title: 'NodeJs',
  src: 'icons8-nodejs-100.svg',
}, {
  title: 'GraphQl',
  src: 'icons8-graphql-100.svg',
}, {
  title: 'REST',
  src: 'icons8-rest-api-100.png',
}, {
  title: 'SASS',
  src: 'icons8-sass-100.svg',
}, {
  title: 'Tailwind',
  src: 'icons8-tailwind-100.svg',
}, {
  title: 'Jest',
  src: 'icons8-jest-100.png',
}, {
  title: 'Webpack',
  src: 'icons8-webpack-100.svg',
}, {
  title: 'AWS',
  src: 'icons8-aws-100.svg',
}, {
  title: 'Firebase',
  src: 'icons8-firebase-100.svg',
}, {
  title: 'Git',
  src: 'icons8-git-100.svg',
}, {
  title: 'Material UI',
  src: 'icons8-material-ui-100.svg',
}, {
  title: 'ANT',
  src: 'ant-256.png',
}, {
  title: 'Auth0',
  src: 'icons8-auth0-100.png',
}, {
  title: 'Stripe',
  src: 'icons8-stripe-100.svg',
}];
